version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    volumes:
      - "mongo:/data/db"
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=collaborator

volumes:
  mongo: